language: java

install: true
script:
- mvn install

notifications:
  email: false

jdk:
- oraclejdk8

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
